#!/bin/bash

#check if environment variable is set

if [-z "$PYFILE"]; then
	echo"Error: PYFILE environment variable not set"
	
	exit 1
fi

	#check if file exists
	
if [! -f "$PYFILE"]; then
	echo"Error: Python file $PYFILE not found"
	exit 1
fi

#Run script
python3 "$PYFILE"
